<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as ORMEntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends ORMEntityRepository
{
	public function getEvents($locale)
	{
		$query = $this->createQueryBuilder('e')->select('e, d')
			->leftJoin('e.event_dates', 'd')
			->setMaxResults(10)
			->getQuery()
			->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale)
			->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker');
		
		return new Paginator($query, $fetchJoinCollection = true);
	}

	public function getEvent($id, $locale)
	{
		return $this->createQueryBuilder('e')->select('e, d')
			->where('e.id = :id')->setParameter('id', $id)
			->leftJoin('e.event_dates', 'd')
			->getQuery()
			->setHint(\Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE, $locale)
			->setHint(\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER, 'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker')
			->getSingleResult();
	}
}
	