<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'userId'       => null,
            'groupId'      => null,
            'pageId'       => null,
            'paginate'      => true,
            'categoryId' => null,
            'locale'        => 'en',
            'locales'       => array_values(array_merge(array('en' => 'en'), array($options['locale'] => $options['locale']))),
            'protagonists'  => false,
            'limit'         => 25,
        ), $options);
    }
    
    public function getArticles(array $options = array())
    {
        $options = self::getOptions($options);
                 
        $count = $this->createQueryBuilder('a')
            ->select('count(a.id)')
            ->leftJoin('a.posts', 'p', 'WITH', 'p.type = '.Post::TYPE_CREATION);

        $query = $this->createQueryBuilder('a')
            ->select('a, t, i, p, l, c, u, lu, cu, pg, gr'.($options['protagonists'] ? ', eu, us' : ''))
            ->leftJoin('a.translations', 't')
            ->leftJoin('a.images', 'i', 'WITH', 'i.main = '.true)
            ->leftJoin('a.posts', 'p', 'WITH', 'p.type = '.Post::TYPE_CREATION)
            ->leftJoin('p.likes', 'l')
            ->leftJoin('p.comments', 'c')
            ->leftJoin('p.user', 'u')
            ->leftJoin('l.user', 'lu')
            ->leftJoin('c.user', 'cu')
            ->leftJoin('p.page', 'pg')
            ->leftJoin('p.group', 'gr')
            ->where('t.locale in (:locales)')->setParameter('locales', $options['locales']);
            
        if ($options['protagonists']) {
            $query->leftJoin('a.entityUsers', 'eu', 'eu.userId')
                ->leftJoin('eu.user', 'us');
        }
        
        if ($options['userId']) {
            $count->andWhere('p.userId = :user_id')->setParameter('user_id', $options['userId']);
            $query->andWhere('p.userId = :user_id')->setParameter('user_id', $options['userId']);
        }
        
        if ($options['pageId']) {
            $count->andWhere('p.pageId = :page_id')->setParameter('page_id', $options['pageId']);
            $query->andWhere('p.pageId = :page_id')->setParameter('page_id', $options['pageId']);
        }
        
        if ($options['groupId']) {
            $count->andWhere('p.groupId = :group_id')->setParameter('group_id', $options['groupId']);
            $query->andWhere('p.groupId = :group_id')->setParameter('group_id', $options['groupId']);
        }
        
        if ($options['categoryId']) {
            $count->andWhere('a.entityCategory = :category_id')
                ->setParameter(':category_id', $options['categoryId']);
            $query->andWhere('a.entityCategory = :category_id')
                ->setParameter(':category_id', $options['categoryId']);
        }

        $count->orderBy('p.createdAt', 'desc');
        $query->orderBy('p.createdAt', 'desc');
        
        return $options['paginate'] ? $query->getQuery()->setHint('knp_paginator.count', $count->getQuery()->getSingleScalarResult()) : $query->setMaxResults($options['limit'])->getQuery()->getResult();
    }

    public function getArticle($id, array $options = array())
    {
        $options = self::getOptions($options);
        
        return $this->createQueryBuilder('a')
            ->select('a, t, i, p, l, c, u, lu, cu, pg, gr, eu, us')
            ->leftJoin('a.translations', 't')
            ->leftJoin('a.images', 'i')
            ->leftJoin('a.posts', 'p', 'WITH', 'p.type = '.Post::TYPE_CREATION)
            ->leftJoin('p.likes', 'l')
            ->leftJoin('p.comments', 'c')
            ->leftJoin('p.user', 'u')
            ->leftJoin('l.user', 'lu')
            ->leftJoin('c.user', 'cu')
            ->leftJoin('p.page', 'pg')
            ->leftJoin('p.group', 'gr')
            ->leftJoin('a.entityUsers', 'eu')
            ->leftJoin('eu.user', 'us')
            ->andWhere('a.id = :id')->setParameter('id', $id)
            ->andWhere('t.locale IN (:locales)')->setParameter('locales', $options['locales'])
            ->getQuery()
            ->getSingleResult();
    }
}