<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiographyRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        $options = array_merge(array(
            'locale'        => 'en'
        ), $options);
        
        return array_merge(array(
            'locales'       => array_values(array_merge(array('en' => 'en'), array($options['locale'] => $options['locale'])))
        ), $options);
    }

    public function getUserBiography($userId, $options = array())
    {
        $options = self::getOptions($options);

        try {
            $biography = $this->createQueryBuilder('b')
                ->select('b, t')
                ->leftJoin('b.translations', 't', 'with', 't.locale IN (:locales)')->setParameter('locales', $options['locales'])
                ->leftJoin('b.post', 'p')
                ->leftJoin('p.user', 'u')
                ->where('u.id = :user_id')->setParameter('user_id', $userId)
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch (\Exception $e) {
            $biography = null;
        }
        return $biography;
    }

    public function getGroupBiography($groupId, $options = array())
    {
        $options = self::getOptions($options);

        try {
            $biography = $this->createQueryBuilder('b')
                ->select('b, t')
                ->leftJoin('b.translations', 't', 'with', 't.locale IN (:locales)')->setParameter('locales', $options['locales'])
                ->leftJoin('b.post', 'p')
                ->leftJoin('p.group', 'g')
                ->where('g.id = :group_id')->setParameter('group_id', $groupId)
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch (\Exception $e) {
            $biography = null;
        }
        return $biography;
    }

    public function getPageBiography($pageId, $options = array())
    {
        $options = self::getOptions($options);

        try {
            $biography = $this->createQueryBuilder('b')
                ->select('b, t')
                ->leftJoin('b.translations', 't', 'with', 't.locale IN (:locales)')->setParameter('locales', $options['locales'])
                ->leftJoin('b.posts', 'p')
                ->leftJoin('p.page', 'pg')
                ->where('pg.id = :page_id')->setParameter('page_id', $pageId)
                ->setMaxResults(1)
                ->getQuery()
                ->getSingleResult();
        } catch (\Exception $e) {
            $biography = null;
        }
        return $biography;
    }
}
