<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiographyRepository extends BaseRepository
{
    public function getUserBiography($userId)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->leftJoin('b.posts', 'p', 'WITH', 'p.type ='.Post::TYPE_CREATION)
            ->leftJoin('p.user', 'u')
            ->where('u.id = :user_id')->setParameter('user_id', $userId)
            ->getQuery()->getResult();
    }
}
