<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends BaseRepository
{
    public function getCommentsFor($type, $postId)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.'.$type.' = :postId')->setParameter('postId', $postId)
            ->getQuery()
            ->getResult();
    }

    public function getComments(array $ids)
    {
        return $this->createQueryBuilder('c')
            ->select('c, u')
            ->join('c.user', 'u')
            ->where('c.id in (:ids)')->setParameter('ids', $ids)
            ->orderBy('c.id', 'desc')
            ->getQuery()
            ->getResult();
    }
}