<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * DiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'userId'       => null,
            'groupId'      => null,
            'pageId'       => null,
            'paginate'      => true,
            'locale'        => 'en',
            'locales'       => array_values(array_merge(array('en' => 'en'), array($options['locale'] => $options['locale']))),
            'protagonists'  => false,
            'limit'         => 25,
        ), $options);
    }
    
    public function getDiscs(array $options = array())
    {
        $options = self::getOptions($options);
                    
        $query = $this->createQueryBuilder('d')
            ->select('d, dt, t, i, p, l, c, u, lu, cu, pg, gr'.($options['protagonists'] ? ', eu, us' : ''))
            ->leftJoin('d.discTracks','dt')
            ->leftJoin('d.translations', 't')
            ->leftJoin('d.images', 'i', 'WITH', 'i.main = '.true)
            ->leftJoin('d.posts', 'p', 'WITH', 'p.type = '.Post::TYPE_CREATION)
            ->leftJoin('p.likes', 'l')
            ->leftJoin('p.comments', 'c')
            ->leftJoin('p.user', 'u')
            ->leftJoin('l.user', 'lu')
            ->leftJoin('c.user', 'cu')
            ->leftJoin('p.page', 'pg')
            ->leftJoin('p.group', 'gr')
            ->where('t.locale in (:locales)')->setParameter('locales', $options['locales']);
            
        if ($options['protagonists']) {
            $query->leftJoin('d.entityUsers', 'eu', 'eu.userId')
                ->leftJoin('eu.user', 'us');
        }
        
        if ($options['userId']) {
            $query->andWhere('p.userId = :user_id')->setParameter('user_id', $options['userId']);
        }
        
        if ($options['pageId']) {
            $query->andWhere('p.pageId = :page_id')->setParameter('page_id', $options['pageId']);
        }
        
        if ($options['groupId']) {
            $query->andWhere('p.groupId = :group_id')->setParameter('group_id', $options['groupId']);
        }

        $query->orderBy('p.updatedAt', 'desc');
        
        return $options['paginate'] ? $query->getQuery() : $query->setMaxResults($options['limit'])->getQuery()->getResult();
    }

    public function getDisc($id, array $options = array())
    {
        $options = self::getOptions($options);
        
        return $this->createQueryBuilder('d')
            ->select('d, t, dt, i, p, l, c, u, lu, cu, pg, gr, eu, us')
            ->leftJoin('d.discTracks', 'dt')
            ->leftJoin('d.translations', 't')
            ->leftJoin('d.images', 'i')
            ->leftJoin('d.posts', 'p', 'WITH', 'p.type = '.Post::TYPE_CREATION)
            ->leftJoin('p.likes', 'l')
            ->leftJoin('p.comments', 'c')
            ->leftJoin('p.user', 'u')
            ->leftJoin('l.user', 'lu')
            ->leftJoin('c.user', 'cu')
            ->leftJoin('p.page', 'pg')
            ->leftJoin('p.group', 'gr')
            ->leftJoin('d.entityUsers', 'eu')
            ->leftJoin('eu.user', 'us')
            ->andWhere('d.id = :id')->setParameter('id', $id)
            ->andWhere('t.locale IN (:locales)')->setParameter('locales', $options['locales'])
            ->getQuery()
            ->getSingleResult();
    }
}
