<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * EducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationRepository extends BaseRepository
{
    public function getLast($id)
    {
        $education = $this->createQueryBuilder('e')
            ->where('e.userId = :id')->setParameter('id', $id)
            ->orderBy('e.dateFrom')
            ->orderBy('e.dateTo')
            ->setMaxResults(1)
            ->getQuery()
            ->getResult();

        if (is_array($education)) {
            $education = $education[0];
        }

        return $education;
    }
}
