<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as ORMEntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends ORMEntityRepository
{
	static protected function getOptions(array $options = array())
	{
		return array_merge(array(
		), $options);
	}
	
    public function getAdmins($entity_id)
	{
        return $this->getEntityManager()->createQueryBuilder()
            ->select('partial eu.{user, entity}')
            ->from('CMBundle:EntityUser','u')
			->where('eu')
			->getQuery()->getResults();
    }
}