<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityUserRepository extends BaseRepository
{
    public function delete($userId, $entityId)
    {
        $this->createQueryBuilder('eu')
            ->delete('CMBundle:EntityUser', 'eu')
            ->where('eu.user = :user_id')->setParameter('user_id', $userId)
            ->andWhere('eu.entity = :entity_id')->setParameter('entity_id', $objectId)
            ->getQuery()
            ->execute();
    }
}
