<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityCategoryRepository extends EntityRepository
{
	static protected function getOptions(array $options = array())
	{
		return array_merge(array(
 			// 'entity_type' => sfContext::getInstance()->getRequest()->getParameter('module'), 
			'user_id'     => null,
 			// 'category'    => sfContext::getInstance()->getRequest()->getParameter('category', null), 
			'paginate'	  => true,
			'locale'	  => 'en',
			'limit'       => 25,
		), $options);
	}
	
	public function filterEntityCategoriesByEntityType($entity_type, array $options = array())
	{
		$options = self::getOptions($options);
		
		return $this->createQueryBuilder('ec')
			->select('ec, ect')
			->leftJoin('ec.translations', 'ect')
			->where('ec.entityType = :entity_type')->setParameter('entity_type', $entity_type)
			->andWhere('ect.locale IN (:locale, \'en\')')->setParameter('locale', $options['locale'])
			->orderBy('ect.name', 'ASC');
	}
	
	public function getEntityCategories(array $options = array())
	{
		return $this->filterEntityCategoriesByEntityType($options)->getQuery()->getResults();
	}
}
