<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRepository extends BaseRepository
{
	static protected function getOptions(array $options = array())
	{
		return array_merge(array(
		), $options);
	}
	
    public function getAdmins($entityId)
	{
        return $this->getEntityManager()->createQueryBuilder()
            ->select('partial eu.{id, entityId, userId}')
            ->from('CMBundle:EntityUser','eu')
            ->where('identity(eu.entity) = :entity_id')->setParameter('entity_id', $entityId)
            ->getQuery()->getResult();
    }

    public function getCreationPost($entityId, $object) {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('p, e, eu')
            ->from('CMBundle:Post', 'p')
            ->leftJoin('p.entity', 'e')
            ->leftJoin('e.entityUsers', 'eu')
            ->where('p.type = '.Post::TYPE_CREATION)
            ->andWhere('p.object = :object')->setParameter('object', $object)
            ->andWhere('e.id = :entity_id')->setParameter('entity_id', $entityId)
            ->getQuery()->getSingleResult();
    }
}