<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as ORMEntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends ORMEntityRepository
{
	public function getEvents($locale)
	{
		$query = $this->createQueryBuilder('e')->select('e, t, d')
			->leftJoin('e.event_dates', 'd')
			->leftJoin('e.translations', 't')
			->where('d.start > :start')->setParameter('start', date('Y-m-d H:i:s', time())) // TODO: use Doctrine for time format!
			->andWhere('t.locale IN (:locale, \'en\')')->setParameter('locale', $locale)
			->setMaxResults(10)
			->getQuery();
		
		return new Paginator($query, $fetchJoinCollection = true);
	}

	public function getEvent($id, $locale)
	{
		return $this->createQueryBuilder('e')->select('e, t, d')
			->leftJoin('e.event_dates', 'd')
			->leftJoin('e.translations', 't')
			->where('e.id = :id')->setParameter('id', $id)
			->andWhere('t.locale IN (:locale, \'en\')')->setParameter('locale', $locale)
			->getQuery()
			->getSingleResult();
	}
}
	