<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupUserRepository extends BaseRepository
{
    public function delete($userId, $groupId)
    {
        $this->createQueryBuilder('eu')
            ->delete('CMBundle:GroupUser', 'gu')
            ->where('gu.user = :user_id')->setParameter('user_id', $userId)
            ->andWhere('gu.group = :group_id')->setParameter('group_id', $groupId)
            ->getQuery()
            ->execute();
    }
}
