<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends EntityRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
        ), $options);
    }

    public function filterGroupsForUser($user_id)
    {
        return $this->createQueryBuilder('g')
            ->select('g')
            ->leftJoin('g.groupUsers', 'gu')
            ->where('gu.user = :user_id')->setParameter('user_id', $user_id);
    }

    public function getGroupsForUser($user_id)
    {
        return $this->filterGroupsForUser($user_id)->getQuery()->getResult();
    }

    public function getUserIdsFor($group_id, $excludes = array())
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('DISTINCT u.id')->from('CMBundle:User', 'u')
            ->leftJoin('u.userGroups', 'ug')
            ->where('ug.group = :group_id')->setParameter('group_id', $group_id);
        if (count($excludes) > 0) {
            $query->andWhere('u.id NOT IN (:excludes)')->setParameter('excludes', $excludes);
        }
        return array_map(function ($user) { return $user['id']; }, $query->getQuery()->getResult());
    }
}