<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * HomepageBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageBannerRepository extends BaseRepository
{
    public function getBanners($offset, $limit)
    {
        return $this->createQueryBuilder('b')
            ->select('b')
            ->orderBy('b.position')
            ->setFirstResult($offset)
            ->setMaxResults($limit)
            ->getQuery()
            ->getResult();
    }

    public function getRandBanners($count)
    {
        $banners = $this->createQueryBuilder('b')
            ->select('b')
            ->getQuery()
            ->getResult();

        if (count($banners) == 0) return null;

        shuffle($banners);
        $banners = array_slice($banners, 0, $count);

        return $this->createQueryBuilder('b')
            ->select('partial b.{id, img}')
            ->orderBy('b.position')
            ->where('b.id in (:ids)')->setParameter('ids', array_map(function($i) { return $i->getId(); }, $banners))
            ->getQuery()
            ->getResult();
    }
}
