<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeRepository extends EntityRepository
{
    public function checkIfUserLikesIt($user, $type, $id)
    {
        return $this->createQueryBuilder('l')
            ->select('COUNT(l)')
            ->where('l.'.$type.' = :id')->setParameter('id', $id)
            ->andWhere('l.user = :user')->setParameter('user', $user)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function whoLikesIt($type, $id)
    {
        return $this->createQueryBuilder('l')
            ->select('l')
            ->where('l.'.$type.' = :id')->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
    