<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'userId' => null,
            'pageId' => null,
            'paginate' => true,
            'limit' => null
        ), $options);
    }

    public function getLinks($options = array())
    {
        $options = self::getOptions($options);

        $query = $this->createQueryBuilder('m')
            ->select('m, p, c, cu, l, lu')
            ->leftJoin('m.posts', 'p', 'with', 'p.type = '.Post::TYPE_CREATION)
            ->leftJoin('p.comments', 'c')
            ->leftJoin('c.user', 'cu')
            ->leftJoin('p.likes', 'l')
            ->leftJoin('l.user', 'lu');

        if (!is_null($options['userId'])) {
            $query->andWhere('p.userId = :user_id')->setParameter('user_id', $options['userId'])
                ->andWhere('p.pageId is NULL');
        }
        if (!is_null($options['pageId'])) {
            $query->andWhere('p.pageId = :page_id')->setParameter('page_id', $options['pageId']);
        }

        if (is_null($options['paginate']) && !is_null($options['limit'])) {
            $query->setMaxResults($options['limit']);
        }
        $query->orderBy('p.createdAt', 'desc');

        return $options['paginate'] ? $query->getQuery() : $query->getQuery()->getResult();
    }

    public function getLink($id, $options = array())
    {
        $options = self::getOptions($options);

        $query = $this->createQueryBuilder('m')
            ->select('m, p, c, cu, l, lu')
            ->leftJoin('m.posts', 'p', 'with', 'p.type = '.Post::TYPE_CREATION)
            ->leftJoin('p.comments', 'c')
            ->leftJoin('c.user', 'cu')
            ->leftJoin('p.likes', 'l')
            ->leftJoin('l.user', 'lu')
            ->where('m.id = :id')->setParameter('id', $id);

        if (!is_null($options['userId'])) {
            $query->andWhere('p.userId = :user_id')->setParameter('user_id', $options['userId'])
                ->andWhere('p.pageId is NULL');
        }
        if (!is_null($options['pageId'])) {
            $query->andWhere('p.pageId = :page_id')->setParameter('page_id', $options['pageId']);
        }

        $link = $query->setMaxResults(1)->getQuery()->getResult();
        if (is_array($link) && count($link) > 0) {
            $link = $link[0];
        } else {
            $link = null;
        }
        return $link;
    }
}
