<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'userId' => null,
            'pageId' => null,
            'paginate' => true,
            'limit'    => 25,
        ), $options);
    }

    public function getPages($options = array())
    {
        $options = self::getOptions($options);

        $count = $this->createQueryBuilder('p')
            ->select('count(p.id)')
            ->innerJoin('p.pageUsers', 'pu', '', '', 'pu.userId');
        $query = $this->createQueryBuilder('p')
            ->select('p, pu, i')
            ->innerJoin('p.pageUsers', 'pu', '', '', 'pu.userId')
            ->leftJoin('p.images', 'i');

        if ($options['userId']) {
            $count->andWhere('pu.userId = :user_id')->setParameter('user_id', $options['userId'])
                ->andWhere('pu.status in (:status)')
                ->setParameter('status', array(PageUser::STATUS_PENDING, PageUser::STATUS_ACTIVE, PageUser::STATUS_REQUESTED));
            $query->andWhere('pu.userId = :user_id')->setParameter('user_id', $options['userId'])
                ->andWhere('pu.status in (:status)')
                ->setParameter('status', array(PageUser::STATUS_PENDING, PageUser::STATUS_ACTIVE, PageUser::STATUS_REQUESTED));
        }

        if ($options['pageId']) {
            $query->andWhere('pu.pageId = :page_id')->setParameter('page_id', $options['pageId']);
        }

        return $options['paginate'] ? $query->getQuery()->setHint('knp_paginator.count', $count->getQuery()->getSingleScalarResult()) : $query->setMaxResults($options['limit'])->getQuery()->getResult();
    }

    public function getAdmins($pageId)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('u')
            ->from('CMBundle:User', 'u')
            ->leftJoin('u.userPages', 'ug')
            ->where('ug.admin = '.true)
            ->andWhere('identity(ug.page) = :page_id')->setParameter('page_id', $pageId)
            ->getQuery()->getResult();
    }

    public function getCreationPost($pageId, $object) {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('p, g, gu')
            ->from('CMBundle:Post', 'p')
            ->leftJoin('p.page', 'g')
            ->leftJoin('g.pageUsers', 'gu')
            ->where('p.type = '.Post::TYPE_CREATION)
            ->andWhere('g.id = :page_id')->setParameter('page_id', $pageId)
            ->getQuery()->getSingleResult();
    }

    public function getPageExcludeUsers($pageId, $excludes)
    {
        return $this->createQueryBuilder('g')
            ->select('g, gu, u')
            ->leftJoin('g.pageUsers', 'gu')
            ->leftJoin('gu.user', 'u')
            ->where('g.id = :page_id')->setParameter('page_id', $pageId)
            ->andWhere('u.id NOT IN (:excludes)')->setParameter('excludes', $excludes)
            ->getQuery()->getSingleResult();
    }

    public function filterPagesForUser($userId)
    {
        return $this->createQueryBuilder('g')
            ->select('g')
            ->leftJoin('g.pageUsers', 'gu')
            ->where('gu.user = :user_id')->setParameter('user_id', $userId);
    }

    public function getPagesForUser($userId)
    {
        return $this->filterPagesForUser($userId)->getQuery()->getResult();
    }

    public function getUserIdsFor($pageId, $excludes = array())
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('DISTINCT u.id')
            ->from('CMBundle:User', 'u')
            ->leftJoin('u.userPages', 'ug')
            ->where('ug.page = :page_id')->setParameter('page_id', $pageId);
        if (count($excludes) > 0) {
            $query->andWhere('u.id NOT IN (:excludes)')->setParameter('excludes', $excludes);
        }
        return array_map(function ($user) { return $user['id']; }, $query->getQuery()->getResult());
    }

    public function search($q, $limit)
    {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->orWhere('p.name LIKE :query')
            ->orWhere('p.name LIKE :Squery')
            ->setParameter('query', $q.'%')
            ->setParameter('Squery', '% '.$q.'%')
            ->setMaxResults($limit)
            ->getQuery()->getResult();
    }

    public function remove($id)
    {
        return $this->createQueryBuilder('p')
            ->delete('CMBundle:Pape', 'p')
            ->where('p.id = :id')->setParameter('id', $id)
            ->petQuery()->execute();
    }
}