<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageUserRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'paginate'      => true,
            'limit'         => 25,
        ), $options);
    }

    public function getMembers($pageId, $options = array())
    {
        $options = self::getOptions($options);
        
        $query = $this->createQueryBuilder('gu')
            ->select('gu')
            ->leftJoin('gu.user', 'u')
            ->where('gu.status = '.PageUser::STATUS_ACTIVE)
            ->andWhere('gu.pageId = :page_id')->setParameter('page_id', $pageId)
            ->orderBy('gu.admin', 'desc');

        return $options['paginate'] ? $query->getQuery() : $query->setMaxResults($options['limit'])->getQuery()->getResult();
    }

    public function delete($userId, $pageId)
    {
        $this->createQueryBuilder('gu')
            ->delete('CMBundle:PageUser', 'gu')
            ->where('gu.user = :user_id')->setParameter('user_id', $userId)
            ->andWhere('gu.page = :page_id')->setParameter('page_id', $pageId)
            ->getQuery()
            ->execute();
    }
}
