<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageUserRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'paginate'      => true,
            'limit'         => 25,
            'status' => array(PageUser::STATUS_ACTIVE)
        ), $options);
    }

    public function getMembers($pageId, $options = array())
    {
        $options = self::getOptions($options);
        
        $query = $this->createQueryBuilder('pu')
            ->select('pu')
            ->leftJoin('pu.user', 'u')
            ->leftJoin('pu.page', 'g')
            ->where('pu.status in (:status)')->setParameter('status', $options['status'])
            ->andWhere('pu.pageId = :page_id')->setParameter('page_id', $pageId)
            ->andWhere('pu.userId != g.creatorId')
            ->orderBy('pu.admin', 'desc');

        return $options['paginate'] ? $query->getQuery() : $query->setMaxResults($options['limit'])->getQuery()->getResult();
    }

    public function updateUserTags($id, array $userTags)
    {  
        $this->createQueryBuilder('pu')
            ->update('CMBundle:PageUser', 'pu')
            ->where('pu.id = :id')->setParameter('id', $id)
            ->set('pu.userTags', '\''.implode(',', $userTags).'\'')
            ->getQuery()->execute();
    }

    public function delete($userId, $pageId)
    {
        $this->createQueryBuilder('pu')
            ->delete('CMBundle:PageUser', 'pu')
            ->where('pu.user = :user_id')->setParameter('user_id', $userId)
            ->andWhere('pu.page = :page_id')->setParameter('page_id', $pageId)
            ->getQuery()
            ->execute();
    }
}
