<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends BaseRepository
{
    public function getEntity($entityId)
    {
        return $this->createQueryBuilder('p')
            ->select('p, e')
            ->leftJoin('p.entity', 'e')
            ->where('e.id = :id')->setParameter('id', $entityId)
            ->getQuery()->getSingleResult();
    }

    public function delete($creatorId, $userId, $object, $objectIds, $entityId = null)
    {
        $query = $this->createQueryBuilder('p')
            ->delete('CMBundle:Post', 'p')
            ->where('p.creator = :creator_id')->setParameter('creator_id', $creatorId)
            ->andWhere('p.user = :user_id')->setParameter('user_id', $userId)
            ->andWhere('p.object = :object')->setParameter('object', $object);
        if (!is_null($entityId)) {
            $query->andWhere('p.entity = :entity_id')->setParameter('entity_id', $entityId);
        } else {
            $query->andWhere('p.objectIds = :object_ids')->setParameter('object_ids', $objectIds);
        }
        // TODO: make it usable for images
        $query->getQuery()->execute();
    }
}
