<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends BaseRepository
{
    public function getEntity($entityId)
    {
        return $this->createQueryBuilder('p')
            ->select('p, e')
            ->leftJoin('p.entity', 'e')
            ->where('e.id = :id')->setParameter('id', $entityId)
            ->getQuery()->getSingleResult();
    }
}
