<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * RelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationTypeRepository extends BaseRepository
{
    public function getTypesPerUser($userId)
    {
        return $this->createQueryBuilder('rt')
            ->select('rt')
            ->where('rt.userId is null')
            ->orWhere('rt.userId = :user_id')->setParameter('user_id', $userId)
            ->orderBy('rt.userId', 'desc')
            ->getQuery()->getResult();
    }
}
