<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * RelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationTypeRepository extends BaseRepository
{
    public function getTypesPerUser($user1Id, $user2Id)
    {
        return $this->createQueryBuilder('rt')
            ->select('rt, r')
            ->leftJoin('rt.relations', 'r', 'with', '(r.userId = :user_1_id AND r.fromUserId = :user_2_id) OR (r.userId = :user_2_id AND r.fromUserId = :user_1_id)')
            ->setParameter('user_1_id', $user1Id)
            ->setParameter('user_2_id', $user2Id)
            ->orderBy('rt.id')
            ->getQuery()->getResult();
    }
}
