<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * SponsoredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsoredRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        $options = array_merge(array(
            'locale' => 'en'
        ), $options);
        
        return array_merge(array(
            'locales' => array_values(array_merge(array('en' => 'en'), array($options['locale'] => $options['locale']))),
            'paginate' => true,
            'limit' => null,
        ), $options);
    }

    public function getLessViewed($options = array())
    {
        $options = self::getOptions($options);

        $count = $this->createQueryBuilder('s')
            ->select('count(s.id)');

        $query = $this->createQueryBuilder('s')
            ->select('s, e, t, c, ct, i, p, pl, pc, plu, pcu')
            ->join('s.entity', 'e')
            ->leftJoin('e.translations', 't', 'with', 't.locale in (:locales)')->setParameter('locales', $options['locales'])
            ->leftJoin('e.entityCategory', 'c')
            ->leftJoin('c.translations', 'ct', 'with', 'ct.locale = :locale')->setParameter('locale', $options['locale'])
            ->leftJoin('e.images', 'i', 'with', 'i.main = '.true)
            ->join('e.posts', 'p', 'with', 'p.type = '.Post::TYPE_CREATION.' AND p.object in (:objects)')
            ->setParameter('objects', array(Event::className(), Disc::className(), ImageAlbum::className(), Multimedia::className(), Article::className(), Link::className()))
            ->leftJoin('p.likes', 'pl')
            ->leftJoin('p.comments', 'pc', '', '', 'pc.id')
            ->leftJoin('pl.user', 'plu')
            ->leftJoin('pc.user', 'pcu')
            ->orderBy('s.views');

        return $options['paginate'] ? $query->getQuery()->setHint('knp_paginator.count', $count->getQuery()->getSingleScalarResult()) : $query->getQuery()->getResult();
    }
}
