<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'type' => null,
            'locale' => 'en'
        ), $options);
    }
    
    public function filterTags(array $options = array())
    {
        $options = self::getOptions($options);
        
        $query = $this->getEntityManager()->createQueryBuilder()->select('t, tt')
            ->from('CMBundle:Tag', 't', 't.id')
            ->leftJoin('t.translations', 'tt')
            ->andWhere('tt.locale IN (:locale, \'en\')')->setParameter('locale', $options['locale']);

        if (!is_null($options['type'])) {
             $query->andWhere('bit_and(t.type, :type) > 0')->setParameter('type', $options['type']);
         }

        return $query;
    }
    
    public function getTags(array $options = array())
    {
        return $this->filterTags($options)->getQuery()->getResult();
    }
}
