<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
            'type' => null,
            'locale' => 'en'
        ), $options);
    }
    
    public function filterTags(array $options = array())
    {
        $options = self::getOptions($options);
        
        $query = $this->getEntityManager()->createQueryBuilder()->select('tg, t')
            ->from('CMBundle:Tag', 'tg', 'tg.id')
            ->leftJoin('tg.translations', 't')
            ->andWhere('t.locale IN (:locale, \'en\')')->setParameter('locale', $options['locale']);

        switch ($options['type']) {
             case 'user':
                 $query->andWhere('t.isUser = '.true);
                 break;
             case 'page':
                 $query->andWhere('t.isPage = '.true);
                 break;
         }

        return $query;
    }
    
    public function getTags(array $options = array())
    {
        return $this->filterTags()->getQuery()->getResult();
    }
}
