<?php

namespace CM\CMBundle\Entity;

use Doctrine\ORM\EntityRepository as BaseRepository;

/**
 * EntityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTagRepository extends BaseRepository
{
    static protected function getOptions(array $options = array())
    {
        return array_merge(array(
             // 'entity_type' => sfContext::getInstance()->getRequest()->getParameter('module'),
             // 'category'    => sfContext::getInstance()->getRequest()->getParameter('category', null),
            'locale'      => 'en'
        ), $options);
    }
    
    public function filterUserTags(array $options = array())
    {
        $options = self::getOptions($options);
        
        return $this->getEntityManager()->createQueryBuilder()->select('tg, t')
            ->from('CM\CMBundle\Entity\UserTag', 'tg', 'tg.id')
            ->leftJoin('tg.translations', 't')
            ->andWhere('t.locale IN (:locale, \'en\')')->setParameter('locale', $options['locale']);
    }
    
    public function getUserTags(array $options = array())
    {
        return $this->filterUserTags()->getQuery()->getResult();
    }
}
