cm_event_homepage:
    pattern:  /
    defaults: { _controller: CMBundle:Event:index }
    
cm_event_show:
    pattern:  /{id}
    defaults: { _controller: CMBundle:Event:show }
    requirements:
        id: \d+
    
cm_event_new:
    pattern:  /new
    defaults: { _controller: CMBundle:Event:new }

    
cm_event_create:
    pattern:  /create
    defaults: { _controller: CMBundle:Event:create }
    requirements:
        _method: POST
