services:
    cm_user.registration.form.type:
        class: CM\UserBundle\Form\UserRegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cm_userbundle_user_registration }