imports:
    - { resource: security.yml }

parameters:
    cm_property_accessor.class: CM\CMBundle\PropertyAccess\CMPropertyAccessor
    bundle.dir: /bundles/cm
    upload.dir: %bundle.dir%/uploads
    images.dir: %upload.dir%/images
    images_full.dir: %images.dir%/full # if you change this, change it also in the Entity/Image.php file!
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: CM\CMBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: cm_cmbundle_user_registration
    profile:
        form:
            type: cm_cmbundle_user_profile

# Translatable form
a2lix_translation_form:
    default_required: false
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"

# KNP Paginator    
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

liip_imagine:
    cache_mkdir_mode: 0755
    web_root: %kernel.root_dir%/../web
    data_root: %kernel.root_dir%/../web%images_full.dir%
    cache_prefix: %images.dir%
    cache_clearer: false
    filter_sets:
        350:
            quality: 100
            filters:
                thumbnail: { size: [350, 350], mode: inset }
        750:
            quality: 100
            filters:
                thumbnail: { size: [750, 750], mode: inset }

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

services:
    property_accessor:
        class: %cm_property_accessor.class%

    cm.twig.cm_extension:
        class: CM\CMBundle\Twig\CMExtension
        arguments: 
            translator: @translator
            userAuthentication: @cm_user.authentication
            options: 
                images_dir: %kernel.root_dir%/../web%images_full.dir%
                sizes: %liip_imagine.filter_sets% 
        tags:
            - { name: twig.extension }
            
    cm.locale_listener:
        class: CM\CMBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    cm_user.authentication:
        class: CM\CMBundle\Service\UserAuthentication
        arguments:
            securityContext: @security.context
            session: @session
            entityManager: @doctrine.orm.entity_manager

    cm_user.registration.type:
        class: CM\CMBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cm_cmbundle_user_registration }
            
    cm_user.profile.type:
        class: CM\CMBundle\Form\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cm_cmbundle_user_profile }