# Translatable form
a2lix_translation_form:
    default_required: false
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"
    
parameters:
    bundle.dir: /bundles/cm
    upload.dir: /uploads
    uploads.images_full: %upload.dir%/images/full # if you change this, change it also in the Image.php file!