# Translatable form
a2lix_translation_form:
    default_required: false
    manager_registry: doctrine
    templating: "A2lixTranslationFormBundle::default.html.twig"

# KNP Paginator    
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

liip_imagine:
    filter_sets:
        entity:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        page:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        group:
            quality: 100
            filters:
                thumbnail: { size: [120, 90], mode: outbound }

parameters:
    bundle.dir: /bundles/cm
    upload.dir: /uploads
    uploads.images_full: %bundle.dir%/%upload.dir%/images/full # if you change this, change it also in the Image.php file!