imports:
    - { resource: security.yml }

parameters:
    web.abs_dir: %kernel.root_dir%/../web
    cm_property_accessor.class: CM\CMBundle\PropertyAccess\CMPropertyAccessor
    bundle.dir: ''
    upload.dir: %bundle.dir%/uploads
    banners.dir: %upload.dir%/banners
    images.dir: %upload.dir%/images
    images_full.dir: %images.dir%/full # if you change this, change it also in the Entity/Image.php file!
    audio.dir: %upload.dir%/audio
    temp.dir: %kernel.root_dir%/../src/CM/CMBundle/Resources/public/temp
    session.attribute_bag.class: Symfony\Component\HttpFoundation\Session\Attribute\NamespacedAttributeBag

assetic:
    # assets:
        # img_bootstrap_glyphicons_black:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/img/glyphicons-halflings.png"
        #     output: "img/glyphicons-halflings.png"

        # img_bootstrap_glyphicons_white:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/img/glyphicons-halflings-white.png"
        # output: "img/glyphicons-halflings-white.png"

        # css_bootstrap:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
        #     output: "css/bootstrap.css"
        #     filters:
        #         - lessphp
        # fonts_bootstrap_eot:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.eot"
        #     output: "fonts/glyphicons-halflings-regular.eot"
        # fonts_bootstrap_woff:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.woff"
        #     output: "fonts/glyphicons-halflings-regular.woff"
        # fonts_bootstrap_ttf:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.ttf"
        #     output: "fonts/glyphicons-halflings-regular.ttf"
        # fonts_bootstrap_svg:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/fonts/glyphicons-halflings-regular.svg"
        #     output: "fonts/glyphicons-halflings-regular.svg"
        # js_bootstrap:
        #     inputs:
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
        #         -  "%kernel.root_dir%/../vendor/twbs/bootstrap/js/*.js"
        #     output: "js/bootstrap.js"

twig:
    globals:
        web_abs_dir: %web.abs_dir%
        banners_dir: %banners.dir%
        uploaded_images_full_dir: %images_full.dir%
        uploaded_audio_dir: %audio.dir%
    form:
        resources:
            - 'CMBundle:Form:compact.html.twig'

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: CM\CMBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: cm_cmbundle_user_registration
    profile:
        form:
            type: cm_cmbundle_user_profile

fos_message:
    db_driver: orm
    thread_class: CM\CMBundle\Entity\MessageThread
    message_class: CM\CMBundle\Entity\Message
    new_thread_form:
      type:    fos_message.new_thread_multiple_form.type
      handler: fos_message.new_thread_multiple_form.handler
      model:   FOS\MessageBundle\FormModel\NewThreadMultipleMessage
      name:    message

# Translatable form
a2lix_translation_form:
    default_required: false
    manager_registry: doctrine
    templating: A2lixTranslationFormBundle::default.html.twig

# KNP Paginator    
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

liip_imagine:
    cache_mkdir_mode: 0755
    web_root: %kernel.root_dir%/../web
    data_root: %kernel.root_dir%/../web%images_full.dir%
    cache_prefix: %images.dir%
    cache_clearer: false
    filter_sets:
        avatar:
            quality: 90
            filters:
                thumbnail_min: { size: 50, mode: inset }
        xsmall:
            quality: 90
            filters:
                thumbnail_min: { size: 125, mode: inset }
        small:
            quality: 90
            filters:
                thumbnail_min: { size: 250, mode: inset }
        medium:
            quality: 90
            filters:
                thumbnail_min: { size: 500, mode: inset }
        large:
            quality: 90
            filters:
                thumbnail_min: { size: 800, mode: inset }
        full:
            quality: 100

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    false

services:
    property_accessor:
        class: %cm_property_accessor.class%

    cm.helper:
        class: CM\CMBundle\Service\Helper
        arguments:
            em: @doctrine.orm.entity_manager
            timezoneDetector: @sonata.intl.timezone_detector
            localeDetector: @sonata.intl.locale_detector

    cm.twig.cm_extension:
        class: CM\CMBundle\Twig\CMExtension
        arguments:
            translator: @translator
            router: @router
            requestStack: @request_stack
            helper: @cm.helper
            securityContext: @security.context
            userAuthentication: @cm.user_authentication
            imagineFilter: @liip_imagine.cache.manager
            options: 
                images_dir: %kernel.root_dir%/../web%images_full.dir%
                sizes: %liip_imagine.filter_sets% 
        tags:
            - { name: twig.extension }

    cm.notification_center:
        class: CM\CMBundle\Service\NotificationCenter
        arguments:
            em: @doctrine.orm.entity_manager

    cm.request_center:
        class: CM\CMBundle\Service\RequestCenter
        arguments:
            em: @doctrine.orm.entity_manager

    cm.post_center:
        class: CM\CMBundle\Service\PostCenter
        arguments:
            em: @doctrine.orm.entity_manager

    cm.doctrine_listener:
        class: CM\CMBundle\EventListener\DoctrineEventsListener
        arguments:
            container: @service_container
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postFlush }
            
    cm.locale_listener:
        class: CM\CMBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    cm.user_authentication:
        class: CM\CMBundle\Service\UserAuthentication
        arguments:
            securityContext: @security.context
            session: @session
            entityManager: @doctrine.orm.entity_manager
            helper: @cm.helper

    cm.form.type.eventdate:
        class: CM\CMBundle\Form\EventDateType
        arguments:
            intl: @sonata.intl.templating.helper.datetime
            helper: @cm.helper
        tags:
            - { name: form.type, alias: cm_cmbundle_eventdate }

    cm.user_registration.type:
        class: CM\CMBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cm_cmbundle_user_registration }
            
    cm.user_profile.type:
        class: CM\CMBundle\Form\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cm_cmbundle_user_profile }

    liip_imagine.filter.loader.thumbnail_min:
        class: CM\CMBundle\Service\ThumbnailMinFilterLoader
        tags:
            - { name: liip_imagine.filter.loader, loader: thumbnail_min }