cm_cmbundle_locale:
    resource: "CM\\CMBundle\\Controller\\LocaleController"
    type:     annotation

cm_cmbundle_wall:
    resource: "CM\\CMBundle\\Controller\\WallController"
    type:     annotation

cm_cmbundle_fan:
    resource: "CM\\CMBundle\\Controller\\FanController"
    type:     annotation

cm_cmbundle_like:
    resource: "CM\\CMBundle\\Controller\\LikeController"
    type:     annotation

cm_cmbundle_comment:
    resource: "CM\\CMBundle\\Controller\\CommentController"
    type:     annotation

cm_cmbundle_request:
    resource: "CM\\CMBundle\\Controller\\RequestController"
    type:     annotation

cm_cmbundle_event:
    resource: "CM\\CMBundle\\Controller\\EventController"
    type:     annotation

cm_cmbundle_page:
    resource: "CM\\CMBundle\\Controller\\PageController"
    type:     annotation

cm_cmbundle_group:
    resource: "CM\\CMBundle\\Controller\\GroupController"
    type:     annotation

cm_cmbundle_entityuser:
    resource: "CM\\CMBundle\\Controller\\EntityUserController"
    type:   

cm_cmbundle_imagealbum:
    resource: "CM\\CMBundle\\Controller\\ImageAlbumController"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /account

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /account/password_reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account/change_password

# admin:
#     resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#     prefix: /admin

# _sonata_admin:
#     resource: .
#     type: sonata_admin
#     prefix: /admin

_imagine:
    resource: .
    type: imagine

cm_cmbundle_user:
    resource: "CM\\CMBundle\\Controller\\UserController"
    type:     annotation