cm_cmbundle_locale:
    resource: "CM\\CMBundle\\Controller\\LocaleController"
    type:     annotation

cm_cmbundle_file_server:
    resource: "CM\\CMBundle\\Controller\\FileServerController"
    type:     annotation

cm_cmbundle_search:
    resource: "CM\\CMBundle\\Controller\\SearchController"
    type:     annotation

cm_cmbundle_fan:
    resource: "CM\\CMBundle\\Controller\\FanController"
    type:     annotation

cm_cmbundle_relation:
    resource: "CM\\CMBundle\\Controller\\RelationController"
    type:     annotation

cm_cmbundle_like:
    resource: "CM\\CMBundle\\Controller\\LikeController"
    type:     annotation

cm_cmbundle_comment:
    resource: "CM\\CMBundle\\Controller\\CommentController"
    type:     annotation

cm_cmbundle_request:
    resource: "CM\\CMBundle\\Controller\\RequestController"
    type:     annotation

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /fos/messages

cm_cmbundle_message:
    resource: "CM\\CMBundle\\Controller\\MessageController"
    type:     annotation

cm_cmbundle_notification:
    resource: "CM\\CMBundle\\Controller\\NotificationController"
    type:     annotation

cm_cmbundle_event:
    resource: "CM\\CMBundle\\Controller\\EventController"
    type:     annotation

cm_cmbundle_disc:
    resource: "CM\\CMBundle\\Controller\\DiscController"
    type:     annotation

cm_cmbundle_imagealbum:
    resource: "CM\\CMBundle\\Controller\\ImageAlbumController"
    type:     annotation

cm_cmbundle_image:
    resource: "CM\\CMBundle\\Controller\\ImageController"
    type:     annotation

cm_cmbundle_multimedia:
    resource: "CM\\CMBundle\\Controller\\MultimediaController"
    type:     annotation

cm_cmbundle_article:
    resource: "CM\\CMBundle\\Controller\\ArticleController"
    type:     annotation

cm_cmbundle_link:
    resource: "CM\\CMBundle\\Controller\\LinkController"
    type:     annotation

cm_cmbundle_entityuser:
    resource: "CM\\CMBundle\\Controller\\EntityUserController"
    type:     annotation

cm_cmbundle_biography:
    resource: "CM\\CMBundle\\Controller\\BiographyController"
    type:     annotation

cm_cmbundle_education:
    resource: "CM\\CMBundle\\Controller\\EducationController"
    type:     annotation

cm_cmbundle_work:
    resource: "CM\\CMBundle\\Controller\\WorkController"
    type:     annotation

cm_cmbundle_page:
    resource: "CM\\CMBundle\\Controller\\PageController"
    type:     annotation

cm_cmbundle_pageuser:
    resource: "CM\\CMBundle\\Controller\\PageUserController"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    defaults:  { _controller: FOSUserBundle:Profile:edit }
    path: /account

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /account/password_reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /account/change_password

# admin:
#     resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
#     prefix: /admin

# _sonata_admin:
#     resource: .
#     type: sonata_admin
#     prefix: /admin

_imagine:
    resource: .
    type: imagine

cm_cmbundle_wall:
    resource: "CM\\CMBundle\\Controller\\WallController"
    type:     annotation

cm_cmbundle_contacts:
    resource: "CM\\CMBundle\\Controller\\ContactsController"
    type:     annotation

cm_cmbundle_staticpages:
    resource: "CM\\CMBundle\\Controller\\StaticPagesController"
    type:     annotation

cm_cmbundle_user:
    resource: "CM\\CMBundle\\Controller\\UserController"
    type:     annotation