parameters:
    cm_property_accessor.class: CM\CMBundle\PropertyAccess\CMPropertyAccessor

services:
    property_accessor:
        class: %cm_property_accessor.class%
    locale_converter:
        class: CM\CMBundle\Request\ParamConverter\LocaleParamConverter
        tags:
            - { name: request.param_converter, priority: 10, converter: locale_converter }