parameters:

services:
    cm.twig.cm_extension:
        class: CM\General\Twig\CMExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }
    cm.locale_listener:
        class: CM\General\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }